### PR TITLE
Chat Integration

### PR DESCRIPTION
**Pull request by AkazaRedSky**
# Major Changes:
- Added websocket integration to Chat

# Minor Changes:
- Sidebar now hoverable
- Fixed chat width
- Fixed All doctor load state

### CODE REVIEW

**Review by danargh — APPROVED** [review]
Mantap bang

**Review by Melkijo — APPROVED** [review]
LGTM 🔥

**Comment by rinehaxor** [comment]
gg kamu jago banget

**Comment by AkazaRedSky** [comment]
usage example: 

https://github.com/Kelompok-3-Capstone-Alterra-2023/Frontend/assets/90970780/0b2e4e3a-9693-427b-87e5-18b1c7e68e5a

**Review by danargh — APPROVED** [review]
Saya lanjut ke fitur obat bang

**Pull request merged**
